# Generated by Django 5.0.7 on 2024-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_user_series_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='series',
            name='platform',
        ),
        migrations.AddField(
            model_name='movie',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.streamingplatform'),
        ),
        migrations.AddField(
            model_name='series',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='series', to='movies.streamingplatform'),
        ),
    ]
